### ISSUE TITLE
[IDEA] Automate the provisioning of a Power Platform environment with creation of the service connection from the Power Platform

### ISSUE THREAD

**Issue by rpothin** [Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit#11]
Other version of the existing issue #8 

To be able to use a Power Platform environment in your ALM process, we need 3 things (if we want to use service principal authentication):

- a Power Platform environment (obviously)
- an application user on your Power Platform environment
- a Power Platform service connection in your Azure DevOps project

Another way to achieve this is by using:
- existing connectors of the Power Platform (ex: Power Platform for Admins for the creation of the environment)
- a custom connector using the Azure DevOps REST API for the management of the service connections

I am still looking a good way create an application user in the new Power Platform environment, but it sure can be done using a UI Flow.

**Comment by BenediktBergmann** [comment]
There are some problems I currently see with the automated provisioning of a CDS environment because those are not possible with the Power Apps Build Tools currently :
- Installing different languages to a new environment 
- Opting in to early access
- Installing additional solutions (ISVs) those have to be stored in the repo as well.

So either we mention those as delimitations, try to fix it with own scripts or use different Build Tools for those.

**Comment by rpothin** [comment]
Indeed, I still do not know how to address these points with an out of the box solution (Power Platform Build Tools, CLI or Power Platform for Admins connector).

The goal of this issue is to provide a canvas app for the provisioning of a Power Platform environment.

I am thinking to use UI Flows for now to address the points you mentioned in your comment. Do you think it could be a good idea @BenediktBergmann ?

**Comment by rpothin** [comment]
As we can trigger Azure DevOps pipelines with parameters from Power Automate, I am not sure it is interesting to provide 2 ways to achieve this goal.

It was interesting to work on a custom connector on this part, but I think I will focus on the issue #8.

Is it ok for you if I close this issue @BenediktBergmann ?

**Comment by BenediktBergmann** [comment]
Yeah sure. Go ahead.
