### ISSUE TITLE
[IDEA] Automate the decommissioning of a Power Platform environment from the Power Platform

### ISSUE THREAD

**Issue by rpothin** [Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit#12]
Other version of the existing issue #9 

When we do not need anymore a Power Platform environment integrated with an Azure DevOps project, we have few things to do:

- delete the Power Platform environment
- delete the Power Platform service connection in the Azure DevOps project

Another way to achieve this is by using:
- existing Power Platform for Admins connector to delete the environment
- a custom connector using the Azure DevOps REST API for the management of the service connections

**Comment by rpothin** [comment]
As we can trigger Azure DevOps pipelines with parameters from Power Automate, I am not sure it is interesting to provide 2 ways to achieve this goal.

It was interesting to work on a custom connector on this part, but I think I will focus on the issue #9.

Is it ok for you if I close this issue @BenediktBergmann ?

**Comment by BenediktBergmann** [comment]
Yeah sure. Go ahead.
