### ISSUE TITLE
[IDEA] YAML files to automate the decommissioning of a Power Platform environment

### ISSUE THREAD

**Issue by rpothin** [Power-Platform-DevOps/Power-Platform-ALM-Starter-Kit#9]
When we do not need anymore a Power Platform environment integrated with an Azure DevOps project, we have few things to do:
- delete the Power Platform environment
- delete the Power Platform service connection in the Azure DevOps project

These points can be address using YAML files.

**Comment by BenediktBergmann** [comment]
Is it possible to delete service connections in Azure DevOps with a YAML file?

**Comment by rpothin** [comment]
Like for the #8 , we can leverage the Azure DevOps CLI to achieve this (https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest#ext-azure-devops-az-devops-service-endpoint-delete).
